### ISSUE TITLE
API endpoints consistency

### ISSUE THREAD

**Issue by ming13** [checkout/checkout-api-reference#42]
Hello there.

[In the reference](https://api-reference.checkout.com/#tag/Tokens/paths/~1tokens/post) I see the following configuration.

* Live — `https://api.checkout.com/tokens`
* Sandbox — `https://api.sandbox.checkout.com/tokens`

Yet [in Android SDK I see different endpoints](https://github.com/checkout/frames-android/blob/3f8b20566b3b0b509eac0576d0281fc0de9010d5/android-sdk/src/main/java/com/checkout/android_sdk/Utils/Environment.java#L4-L5).

* Live — `https://api2.checkout.com/v2/tokens/card/`
* Sandbox — `https://sandbox.checkout.com/api2/v2/tokens/card/`

Which one should be used? Is there a separate documentation for `v2`? 

CC Android SDK developers — @john-ohalloran-cko, @ioan-ghisoi-cko

**Comment by nicolas-maalouf-cko** [comment]
Hi @ming13 ,

The SDKs still use the old endpoint (with v2 in the URL) that generates a card token in the card_tok_xxxxx format. These card tokens are backwards compatible with the new unifier payments API.

We'll update the SDKs at some point but not that this does not break compatibility.

As the reference is correct I'll close this issue, thanks for your suggestion

**Comment by ming13** [comment]
Awesome, thanks!
